name: Deploy to Boltic

on:
  push:
    branches: [main]

env:
  SERVERLESS_NAME: githubcheckcicd

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.BOLTIC_SSH_KEY_B64 }}" | base64 -d > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ssh.git.boltic.io >> ~/.ssh/known_hosts

      - name: Push to Boltic
        run: |
          git remote add boltic git@ssh.git.boltic.io:312fb7be-7a5b-47d7-8563-03635476d7b2/githubcheckcicd.git
          git push boltic main --force
